exclude: ^(data/.*|.vscode/.*|poetry.lock)$

repos:
  - repo: https://github.com/commitizen-tools/commitizen
    # Please run `pre-commit install --hook-type commit-msg` to check commit messages
    rev: v3.13.0
    hooks:
      - id: commitizen

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: check-case-conflict
      - id: check-ast
      - id: check-added-large-files
        args: ["--maxkb=1000"]

  - repo: https://github.com/codespell-project/codespell.git
    rev: v2.2.6
    hooks:
      - id: codespell
        name: codespell

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.4.0
    hooks:
      - id: pycln
        name: pycln (python)
        args: [--config=pyproject.toml]

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        name: pydocstyle

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        name: mypy
        additional_dependencies: ["types-pytz"]

  - repo: https://github.com/pycqa/pylint
    rev: v3.0.3
    hooks:
      - id: pylint
        types: [python]

  - repo: local
    hooks:
      - id: poetry-install
        name: Install project deps
        entry: poetry install
        language: system
        always_run: false
        types: [python]
        pass_filenames: false
        stages: [commit, merge-commit, push, manual]
      - id: run-tests
        name: Run tests
        entry: poetry run pytest
        language: system
        always_run: false
        types: [python]
        pass_filenames: false
        stages: [commit, merge-commit, push, manual]
