plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@bjoluc/semantic-release-config-poetry"
  - "@semantic-release/changelog"
  - - "@semantic-release/exec"
    - prepareCmd: "npx prettier --write CHANGELOG.md; poetry version ${nextRelease.version};"

  - - "@semantic-release/git"
    - assets:
      - "CHANGELOG.md"
      - "pyproject.toml"
      message: "chore(release): ${nextRelease.version} [CI SKIP]\n\n${nextRelease.notes}"

  - "@saithodev/semantic-release-gitea"

tagFormat: "${version}"
branches:
  - "+([0-9])?(.{+([0-9]),x}).x"
  - "master"
  - "main"
  - "next"
  - "next-major"

  - "name": "beta"
    "prerelease": true

  - "name": "alpha"
    "prerelease": true
