version: "0.2"
allowCompoundWords: true
ignorePaths:
  - .pre-commit-config.yaml
  - pyproject.toml
  - .gitlab-ci.yml
  - cspell.config.yaml
  - .vscode/*
  - .mypy.ini
  - .gitignore
  - .releaserc
  - CHANGELOG.md
  - .drone.yml
dictionaryDefinitions: []
ignoreWords:
  - Aelon
  - ansi
  - cifs
  - fhnw
  - FHNW
  - fromb
  - idDiv_SAOTCAS_Title
  - loginfmt
  - NBSWY3DPEB3W64TMMQ
  - ocma
  - OCMA
  - otpauth
  - otppy
  - pipx
  - pyproject
  - SAOTCC
  - totp
  - TOTP
  - xvzf
dictionaries: []
words: []
import:
  - "@cspell/dict-de-ch/cspell-ext.json"
  - "@cspell/dict-en-gb/cspell-ext.json"
