version: "0.2"
allowCompoundWords: false
ignorePaths:
  - "*.svg"
  - .pre-commit-config.yaml
  - .vscode/*
  - .gitignore
  - cspell.config.yaml
  - .copier-answers.yml
  - "*.svg"
  - .renovate.json
  - .woodpecker/*
  - .releaserc.yaml
  - CHANGELOG.md
  - .mypy.ini
  - pyproject.toml
dictionaryDefinitions: []
ignoreWords: []
dictionaries: []
words:
  - 3Aelon
  - ansi
  - cifs
  - fhnw
  - firefox
  - fromb32
  - geckodriver
  - hadolint
  - interactable
  - Interactable
  - kwargs
  - levelname
  - loginfmt
  - microsoftonline
  - NBSWY3DPEB3W64TMMQ
  - ocma
  - openconnect
  - Openconnect
  - Openconnect ms auth
  - openconnect_ms_auth
  - openvpn
  - otpauth
  - otppy
  - pipefail
  - pipx
  - pylint
  - pyproject
  - PYTHONPATH
  - SAOTCAS
  - SAOTCC
  - totp
  - webvpn
  - xvzf
import:
  - "@cspell/dict-de-ch/cspell-ext.json"
  - "@cspell/dict-en-gb/cspell-ext.json"
