[tool.poetry]
name = "ocma"
version = "0.3.0"
description = ""
authors = ["Sean Blackburn <birdicode@gmail.com>"]
license = "MIT"
packages = [
  {include = "ocma"},
  {include = "ocma/py.typed"},
]

[tool.poetry.dependencies]
python = "^3.9"
selenium = "^4.1.0"
OTPpy = "^0.1.2"

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
pre-commit = "^3.0.4"
pydocstyle = "^6.1.1"
pylint = "^2.16.2"
mypy = "^1.0.1"
pytest = "^7.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
ocma = 'ocma.cli:run'

[tool.isort]
multi_line_output=9
