when:
  event:
    - push
    - pull_request
    - manual

steps:
  pre-commit:
    image: git.snas.black-burn.ch/sean/poetry-in-a-container:3.11
    volumes:
      - /tmp-woodpecker/cache/poetry:/root/.cache/pypoetry/virtualenvs
      - /tmp-woodpecker/cache/pip:/root/.cache/pip/
      - /tmp-woodpecker/cache/pre_commit_environments:/root/.cache/pre-commit
    commands:
      - poetry install
      - pre-commit run -a

  build-latest:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      username:
        from_secret: NUCNAS_GITEA_DOCKER_USERNAME
      password:
        from_secret: NUCNAS_GITEA_DOCKER_PASSWORD
      repo: git.snas.black-burn.ch/${CI_REPO,,}
      registry: git.snas.black-burn.ch
      platforms: linux/amd64
      auto_tag: true
      when:
        branch:
          exclude:
            - renovate/*
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  semantic-release:
    image: git.snas.black-burn.ch/sean/semantic-release-in-a-container:1
    secrets:
      - GITEA_SEMANTIC_RELEASE_TOKEN
    commands:
      - export GITEA_URL=https://git.snas.black-burn.ch
      - export GITEA_TOKEN=$${GITEA_SEMANTIC_RELEASE_TOKEN}
      - export GIT_CREDENTIALS="Sean:$${GITEA_SEMANTIC_RELEASE_TOKEN}"
      - semantic-release
    when:
      branch:
        - "*.*.x"
        - main
        - master
        - next
        - next-major
        - beta
        - alpha

  notify:
    image: git.snas.black-burn.ch/sean/woodpecker-apprise:1
    when:
      - status: [failure, success]
      - branch:
          exclude:
            - renovate/*
    settings:
      evaluate: "not pipeline.success or not prev_pipeline.success"
      services:
        - url:
            from_secret: APPRISE_NOTIFICATION_URL
      content:
        title: "{% if pipeline.success %}🤠{% else %}🚨{% endif %} | {{ repo.full_name }} ({{ commit.branch }} - {{ commit.sha[0:8] }})"
        body: |
          The pipeline has {% if pipeline.success %}been fixed 🤠{% else %}failed 🚨{% endif %}.

          View Pipeline: {{ pipeline.url }}
          View Repo: {{ repo.url }}
